import { chromium } from '@playwright/test';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newPage({ viewport: { width: 1440, height: 920 } });
await page.goto('http://localhost:4173/');
await page.waitForSelector('[data-testid="library-card"]');
await page.getByTestId('support-btn').click();
await page.getByTestId('support-message').fill('The fit meter says page 2 but my printout is one page.');
await page.waitForTimeout(300);
await page.screenshot({ path: process.env.OUT + '/support-tab.png' });
await browser.close();
